.TH "_audioenvio" 3 "Domingo, 7 de Mayo de 2017" "Version 3.0" "Practica RedesII" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_audioenvio \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cliente\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "char * \fBip\fP"
.br
.ti -1c
.RI "char * \fBnick\fP"
.br
.ti -1c
.RI "short \fBpuerto\fP"
.br
.in -1c
.SH "Documentación de los campos"
.PP 
.SS "char* ip"

.SS "char* nick"

.SS "short puerto"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Practica RedesII del código fuente\&.
