.TH "_audiorecepcion" 3 "Domingo, 7 de Mayo de 2017" "Version 3.0" "Practica RedesII" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_audiorecepcion \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cliente\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "int \fBsocket\fP"
.br
.ti -1c
.RI "void * \fBdireccion\fP"
.br
.in -1c
.SH "Documentación de los campos"
.PP 
.SS "void* direccion"

.SS "int socket"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Practica RedesII del código fuente\&.
