.TH "_datosMensaje" 3 "Domingo, 7 de Mayo de 2017" "Version 3.0" "Practica RedesII" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_datosMensaje \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <funciones_servidor\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "int \fBsckfd\fP"
.br
.ti -1c
.RI "char * \fBmsg\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.in -1c
.SH "Documentación de los campos"
.PP 
.SS "size_t len"

.SS "char* msg"

.SS "int sckfd"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Practica RedesII del código fuente\&.
