.TH "includes/audiochat.h" 3 "Domingo, 7 de Mayo de 2017" "Version 3.0" "Practica RedesII" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/audiochat.h \- 
funciones relacionadas con el envio de audio  

.SH SYNOPSIS
.br
.PP
.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBcerrarAudioSend\fP (void)"
.br
.RI "\fITermina el envio de audio\&. \fP"
.ti -1c
.RI "void * \fBaudiochatSend\fP (void *audio)"
.br
.RI "\fISe encarga del envio de audio\&. \fP"
.ti -1c
.RI "void \fBcerrarAudioRecv\fP (void)"
.br
.RI "\fITermina recepcion del audio\&. \fP"
.ti -1c
.RI "void * \fBaudiochatRecv\fP (void *audio)"
.br
.RI "\fISe encarga de la recepcion de audio\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 
funciones relacionadas con el envio de audio 


.SH "AUTHOR"
.PP
Pablo Marcos pablo.marcos@estudiante.uam.es 
.SH "AUTHOR"
.PP
Dionisio Perez dionisio.perez@estudiante.uam.es 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Practica RedesII del código fuente\&.
