.TH "src/bot_galletas.c" 3 "Domingo, 7 de Mayo de 2017" "Version 3.0" "Practica RedesII" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/bot_galletas.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include '\&.\&./includes/bot\&.h'\fP
.br
\fC#include <redes2/irc\&.h>\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "int \fBbot_galletas\fP (char *mensaje3, char *tar)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Documentación de las funciones"
.PP 
.SS "int bot_galletas (char *mensaje3, char *tar)"

.SS "int main (intargc, char *argv[])"

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Practica RedesII del código fuente\&.
