.TH "includes/comandos_cliente.h" 3 "Domingo, 7 de Mayo de 2017" "Version 3.0" "Practica RedesII" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/comandos_cliente.h \- 
.PP
Funciones para el tratamiento de los comandos de cliente\&.  

.SH SYNOPSIS
.br
.PP
.SS "'typedefs'"

.in +1c
.ti -1c
.RI "typedef void(* \fBcomando_cliente_t\fP )(char *)"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBinicializar_comandos_cliente\fP (void)"
.br
.RI "\fIFuncion de inicializacion del array de comandos de cliente\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBcomando_cliente_t\fP \fBcomandos_cliente\fP [IRC_MAX_USER_COMMANDS]"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Funciones para el tratamiento de los comandos de cliente\&. 


.SH "AUTHOR"
.PP
Pablo Marcos pablo.marcos@estudiante.uam.es 
.SH "AUTHOR"
.PP
Dionisio Perez dionisio.perez@estudiante.uam.es 
.SH "Documentación de los 'typedefs'"
.PP 
.SS "typedef void(* comando_cliente_t)(char *)"

.SH "Documentación de las variables"
.PP 
.SS "\fBcomando_cliente_t\fP comandos_cliente[IRC_MAX_USER_COMMANDS]"

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Practica RedesII del código fuente\&.
