.TH "includes/comandos_noirc.h" 3 "Domingo, 7 de Mayo de 2017" "Version 3.0" "Practica RedesII" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/comandos_noirc.h \- 
.PP
Funciones para el parseo de mensajes de envio de ficheros y audio\&.  

.SH SYNOPSIS
.br
.PP
.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBparse_noIRC\fP (char *comando, char *\fBnick\fP)"
.br
.RI "\fIFuncion de parseo\&. \fP"
.ti -1c
.RI "void \fBparse_fsend\fP (char *comando, char *\fBnick\fP)"
.br
.RI "\fIFuncion de parseo del fsend\&. \fP"
.ti -1c
.RI "void \fBparse_fcancel\fP (char *comando, char *\fBnick\fP)"
.br
.RI "\fIFuncion de parseo del fcancel\&. \fP"
.ti -1c
.RI "void \fBparse_audiochat\fP (char *comando, char *\fBnick\fP)"
.br
.RI "\fIFuncion de parseo del audiochat\&. \fP"
.ti -1c
.RI "void \fBparse_audioexit\fP (char *comando, char *\fBnick\fP)"
.br
.RI "\fIFuncion de parseo del audioexit\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 
Funciones para el parseo de mensajes de envio de ficheros y audio\&. 


.SH "AUTHOR"
.PP
Pablo Marcos pablo.marcos@estudiante.uam.es 
.SH "AUTHOR"
.PP
Dionisio Perez dionisio.perez@estudiante.uam.es 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Practica RedesII del código fuente\&.
