.TH "ComandosCliente" 3 "Domingo, 7 de Mayo de 2017" "Version 3.0" "Practica RedesII" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ComandosCliente \- 
.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBcomando_general\fP (char *comando)"
.br
.RI "\fIFuncion de procesamiento por defecto del comando del cliente\&. \fP"
.ti -1c
.RI "void \fBclientePart\fP (char *comando)"
.br
.RI "\fIFuncion de procesamiento del comando del cliente Part\&. \fP"
.ti -1c
.RI "void \fBclientePartAll\fP (char *comando)"
.br
.RI "\fIFuncion de procesamiento del comando del cliente PartAll\&. \fP"
.ti -1c
.RI "void \fBclienteCycle\fP (char *comando)"
.br
.RI "\fIFuncion de procesamiento del comando del cliente Cycle\&. \fP"
.ti -1c
.RI "void \fBinicializar_comandos_cliente\fP (void)"
.br
.RI "\fIFuncion de inicializacion del array de comandos de cliente\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 

.PP
.PP
Comprende funciones para el tratamiento de los comandos de cliente
.PP
.PP
 
.SH "Documentación de las funciones"
.PP 
.SS "void clienteCycle (char *comando)"

.PP
Funcion de procesamiento del comando del cliente Cycle\&. 
.SH "SYNOPSIS"
.PP
.PP
.nf
void clienteCycle(char *comando)
.fi
.PP
.PP
\fBParámetros:\fP
.RS 4
\fIcomando\fP comando a procesar
.RE
.PP
.SH "AUTHOR"
.PP
Pablo Marcos Manchon Dionisio Perez Alvear
.PP
.PP
 
.SS "void clientePart (char *comando)"

.PP
Funcion de procesamiento del comando del cliente Part\&. 
.SH "SYNOPSIS"
.PP
.PP
.nf
void clientePart(char *comando)
.fi
.PP
.PP
\fBParámetros:\fP
.RS 4
\fIcomando\fP comando a procesar
.RE
.PP
.SH "AUTHOR"
.PP
Pablo Marcos Manchon Dionisio Perez Alvear
.PP
.PP
 
.SS "void clientePartAll (char *comando)"

.PP
Funcion de procesamiento del comando del cliente PartAll\&. 
.SH "SYNOPSIS"
.PP
.PP
.nf
void clientePartAll(char *comando)
.fi
.PP
.PP
\fBParámetros:\fP
.RS 4
\fIcomando\fP comando a procesar
.RE
.PP
.SH "AUTHOR"
.PP
Pablo Marcos Manchon Dionisio Perez Alvear
.PP
.PP
 
.SS "void comando_general (char *comando)"

.PP
Funcion de procesamiento por defecto del comando del cliente\&. 
.SH "SYNOPSIS"
.PP
.PP
.nf
void comando_general(char *comando)
.fi
.PP
.PP
\fBParámetros:\fP
.RS 4
\fIcomando\fP comando a procesar
.RE
.PP
.SH "AUTHOR"
.PP
Pablo Marcos Manchon Dionisio Perez Alvear
.PP
.PP
 
.SS "void inicializar_comandos_cliente (void)"

.PP
Funcion de inicializacion del array de comandos de cliente\&. 
.SH "SYNOPSIS"
.PP
.PP
.nf
void inicializar_comandos_cliente(void)
.fi
.PP
.SH "AUTHOR"
.PP
Pablo Marcos Manchon Dionisio Perez Alvear
.PP
.PP
 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Practica RedesII del código fuente\&.
