.TH "srclib/config.c" 3 "Domingo, 7 de Mayo de 2017" "Version 3.0" "Practica RedesII" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srclib/config.c \- 
.PP
daemonizar y funciones relacionadas con el servidor y descriptores  

.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./includes/config\&.h'\fP
.br
\fC#include '\&.\&./includes/funciones_servidor\&.h'\fP
.br
\fC#include '\&.\&./includes/red_servidor\&.h'\fP
.br
\fC#include '\&.\&./includes/conexion_temp\&.h'\fP
.br
\fC#include '\&.\&./includes/ssl\&.h'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBdaemonizar\fP (char *servicio, int logLevel)"
.br
.RI "\fIDemoniza el proceso\&. \fP"
.ti -1c
.RI "void \fBcerrarDescriptores\fP (void)"
.br
.RI "\fICiera el conjunto de descriptores\&. \fP"
.ti -1c
.RI "void \fBabrirLog\fP (char *identificacion, int logLevel)"
.br
.RI "\fIAbre el log para el envio de mensajes\&. \fP"
.ti -1c
.RI "void \fBmanejadorSIGUSR1\fP (int sennal)"
.br
.RI "\fIManejador de la sennal SIGUSR1\&. \fP"
.ti -1c
.RI "void \fBmanejadorSIGALRM\fP (int sennal)"
.br
.RI "\fIManejador de la sennal SIGALARM\&. \fP"
.ti -1c
.RI "\fBstatus\fP \fBinicializarServidor\fP (void)"
.br
.RI "\fIInicializa el servidor\&. \fP"
.ti -1c
.RI "void \fBcerrarServidor\fP (void)"
.br
.RI "\fICierra el servidor\&. \fP"
.ti -1c
.RI "void \fBmanejadorSigint\fP (int signal)"
.br
.RI "\fIManejador de la sennal SIGINT\&. \fP"
.ti -1c
.RI "\fBstatus\fP \fBinicializarFD\fP (int sckt)"
.br
.RI "\fIInicializa descriptor del socket dado\&. \fP"
.ti -1c
.RI "\fBstatus\fP \fBaddFd\fP (int sckt)"
.br
.RI "\fIAnnade descriptor al conjunto de descriptores activos\&. \fP"
.ti -1c
.RI "\fBstatus\fP \fBdeleteFd\fP (int sckt)"
.br
.RI "\fIElimina descriptor del socket dado\&. \fP"
.ti -1c
.RI "\fBstatus\fP \fBsetReadFD\fP (fd_set *readFD)"
.br
.RI "\fIPone como leido el socket dado\&. \fP"
.ti -1c
.RI "\fBstatus\fP \fBlanzarServidor\fP (unsigned int puerto, short pingpong)"
.br
.RI "\fILanza el servidor\&. \fP"
.ti -1c
.RI "\fBstatus\fP \fBlanzarServidorSSL\fP (unsigned int puerto, short pingpong)"
.br
.RI "\fILanza el servidor con SSL\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 
daemonizar y funciones relacionadas con el servidor y descriptores 


.SH "AUTHOR"
.PP
Pablo Marcos pablo.marcos@estudiante.uam.es 
.SH "AUTHOR"
.PP
Dionisio Perez dionisio.perez@estudiante.uam.es 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Practica RedesII del código fuente\&.
