.TH "includes/file_send.h" 3 "Domingo, 7 de Mayo de 2017" "Version 3.0" "Practica RedesII" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/file_send.h \- 
.PP
Funciones para el envio de archivos\&.  

.SH SYNOPSIS
.br
.PP
.SS "Funciones"

.in +1c
.ti -1c
.RI "void * \fBfile_send_func\fP (void *envioVoid)"
.br
.RI "\fIFuncion que controla el envio de ficheros\&. \fP"
.ti -1c
.RI "void * \fBfile_recv_func\fP (void *recvVoid)"
.br
.RI "\fIFuncion que controla la recepcion de ficheros\&. \fP"
.ti -1c
.RI "void \fBnormalize_file\fP (char *f)"
.br
.RI "\fIFuncion para sustituir en el nombre de archivo espacios en blanco por barras bajas\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 
Funciones para el envio de archivos\&. 


.SH "AUTHOR"
.PP
Pablo Marcos pablo.marcos@estudiante.uam.es 
.SH "AUTHOR"
.PP
Dionisio Perez dionisio.perez@estudiante.uam.es 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Practica RedesII del código fuente\&.
