.TH "includes/irc_cliente.h" 3 "Domingo, 7 de Mayo de 2017" "Version 3.0" "Practica RedesII" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/irc_cliente.h \- 
.PP
Toda la parte de comandos de usuario\&.  

.SH SYNOPSIS
.br
.PP
.SS "Funciones"

.in +1c
.ti -1c
.RI "void * \fBrecv_pthread\fP (void *sckfd)"
.br
.RI "\fIFuncion del hilo de recepcion de mensajes\&. \fP"
.ti -1c
.RI "void \fBinicializar_comandos_recv\fP (void)"
.br
.RI "\fIInicializa el array de comandos\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 
Toda la parte de comandos de usuario\&. 


.SH "AUTHOR"
.PP
Pablo Marcos pablo.marcos@estudiante.uam.es 
.SH "AUTHOR"
.PP
Dionisio Perez dionisio.perez@estudiante.uam.es 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Practica RedesII del código fuente\&.
