.TH "src/servidor.c" 3 "Domingo, 7 de Mayo de 2017" "Version 3.0" "Practica RedesII" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/servidor.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <getopt\&.h>\fP
.br
\fC#include '\&.\&./includes/config\&.h'\fP
.br
\fC#include '\&.\&./includes/funciones_servidor\&.h'\fP
.br
\fC#include '\&.\&./includes/red_servidor\&.h'\fP
.br
\fC#include '\&.\&./includes/ssl\&.h'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBusage\fP (void)"
.br
.RI "\fIImprime por stderr la ayuda de usuario\&. \fP"
.ti -1c
.RI "void \fBwelcome\fP (short daemon, short pingpong, short ssl, short \fBoffensive\fP, int puerto_definido)"
.br
.RI "\fIImprime mensaje de bienvenida\&. \fP"
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Documentación de las funciones"
.PP 
.SS "int main (intargc, char *argv[])"

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Practica RedesII del código fuente\&.
