.TH "Servidor-Cliente-echo" 3 "Domingo, 7 de Mayo de 2017" "Version 3.0" "Practica RedesII" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Servidor-Cliente-echo \- 
.SS "Funciones"

.in +1c
.ti -1c
.RI "int \fBcrearSocketTCP_cliente\fP (int *sckfd, char *server, unsigned short port)"
.br
.RI "\fIFuncion para crear un socket TCP para el cliente echo\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 

.PP
.PP
Comprende los mains para probar tanto el cliente como el servidor echo
.PP
.PP
 
.SH "Documentación de las funciones"
.PP 
.SS "int crearSocketTCP_cliente (int *sckfd, char *server, unsigned shortport)"

.PP
Funcion para crear un socket TCP para el cliente echo\&. 
.SH "SYNOPSIS"
.PP
.PP
.nf
int crearSocketTCP_cliente(int *sckfd, char *server, unsigned short port)
.fi
.PP
.PP
\fBParámetros:\fP
.RS 4
\fIsckfd\fP socket en el que conectar 
.br
\fIserver\fP servidor del que obtener direccion IP 
.br
\fIport\fP puerto al que conectar
.RE
.PP
.SH "AUTHOR"
.PP
Pablo Marcos Manchon Dionisio Perez Alvear
.PP
.PP
 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Practica RedesII del código fuente\&.
