.TH "srclib/ssl.c" 3 "Domingo, 7 de Mayo de 2017" "Version 3.0" "Practica RedesII" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srclib/ssl.c \- 
.PP
Soporte SSL\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <openssl/bio\&.h>\fP
.br
\fC#include <openssl/ssl\&.h>\fP
.br
\fC#include <openssl/err\&.h>\fP
.br
\fC#include '\&.\&./includes/ssl\&.h'\fP
.br

.SS "'defines'"

.in +1c
.ti -1c
.RI "#define \fBCA_FILE_PATH\fP   '\&./certs/ca\&.pem'"
.br
.in -1c
.SS "'typedefs'"

.in +1c
.ti -1c
.RI "typedef SSL * \fBpSSL\fP"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBssl_error\fP (char *msg)"
.br
.RI "\fIImprime mensaje de error si una funcion SSL falla\&. \fP"
.ti -1c
.RI "int \fBinicializar_nivel_SSL\fP ()"
.br
.RI "\fIInicializa nivel SSL\&. \fP"
.ti -1c
.RI "int \fBfijar_contexto_SSL\fP (const char *pcert, const char *pkey)"
.br
.RI "\fICrea contexto SSL y comprueba certificados\&. \fP"
.ti -1c
.RI "int \fBconectar_canal_seguro_SSL\fP (int sckfd)"
.br
.RI "\fISe conecta a un socket con seguridad SSL\&. \fP"
.ti -1c
.RI "int \fBaceptar_canal_seguro_SSL\fP (int sckfd)"
.br
.RI "\fIPermite conexion SSL segura\&. \fP"
.ti -1c
.RI "int \fBevaluar_post_conectar_SSL\fP (int sckfd)"
.br
.RI "\fIevalua seguridad de la conexion \fP"
.ti -1c
.RI "int \fBenviar_datos_SSL\fP (int sckfd, void *mensaje, int tam)"
.br
.RI "\fIenvia mensaje de forma segura por medio de SSL \fP"
.ti -1c
.RI "int \fBrecibir_datos_SSL\fP (int sckfd, void *mensaje, int max)"
.br
.RI "\fIRecibe mensaje de forma segura por medio de SSL\&. \fP"
.ti -1c
.RI "void \fBcerrar_canal_SSL\fP (int sckfd)"
.br
.RI "\fICierra conexion segura SSL\&. \fP"
.ti -1c
.RI "void \fBliberar_nivel_SSL\fP ()"
.br
.RI "\fIElimina contexto SSL creado\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "SSL_CTX * \fBcontext\fP"
.br
.ti -1c
.RI "\fBpSSL\fP \fBSSL_sockets\fP [\fBMAX_SSL\fP] = {0}"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Soporte SSL\&. 


.SH "AUTHOR"
.PP
Pablo Marcos pablo.marcos@estudiante.uam.es 
.SH "AUTHOR"
.PP
Dionisio Perez dionisio.perez@estudiante.uam.es 
.SH "Documentación de los 'defines'"
.PP 
.SS "#define CA_FILE_PATH   '\&./certs/ca\&.pem'"

.SH "Documentación de los 'typedefs'"
.PP 
.SS "typedef SSL* \fBpSSL\fP"

.SH "Documentación de las variables"
.PP 
.SS "SSL_CTX* context"

.SS "\fBpSSL\fP SSL_sockets[\fBMAX_SSL\fP] = {0}"

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Practica RedesII del código fuente\&.
